# Generated by Django 5.1.3 on 2024-11-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="organizer",
        ),
    ]
