from django.core.management.base import BaseCommand
from events.models import Event
from django.utils import timezone

class Command(BaseCommand):
    help = 'Seed the database with 25 specific university-related events in Pittsburgh'

    def handle(self, *args, **kwargs):
        # Bestehende Daten löschen, um Dubletten zu vermeiden
        Event.objects.all().delete()

        # Hardcodierte Events
        events = [
            {
                "title": "Campus Tour",
                "description": "Explore the University of Pittsburgh with a guided campus tour.",
                "time": timezone.now() + timezone.timedelta(days=1),
                "location": "University of Pittsburgh, Cathedral of Learning",
                "type": "Campus Event",
                "tags": "Campus,Students,Community",
                "latitude": 40.4425,
                "longitude": -79.9531,
            },
            {
                "title": "AI Research Seminar",
                "description": "Learn about the latest advancements in Artificial Intelligence.",
                "time": timezone.now() + timezone.timedelta(days=2),
                "location": "University of Pittsburgh, Information Science Building",
                "type": "Academic",
                "tags": "Research,Technology,Students",
                "latitude": 40.4445,
                "longitude": -79.9562,
            },
            {
                "title": "Football Night",
                "description": "Join us for a thrilling football game at Heinz Field.",
                "time": timezone.now() + timezone.timedelta(days=3),
                "location": "Heinz Field, Pittsburgh",
                "type": "Sports",
                "tags": "Sports,Community,Students",
                "latitude": 40.4470,
                "longitude": -80.0150,
            },
            {
                "title": "Pitt Arts Night",
                "description": "Experience an evening filled with art and culture at Pitt.",
                "time": timezone.now() + timezone.timedelta(days=4),
                "location": "University of Pittsburgh, Frick Fine Arts Building",
                "type": "Cultural",
                "tags": "Arts,Culture,Community",
                "latitude": 40.4416,
                "longitude": -79.9559,
            },
            {
                "title": "Entrepreneurship Workshop",
                "description": "Learn the basics of starting your own business.",
                "time": timezone.now() + timezone.timedelta(days=5),
                "location": "University of Pittsburgh, Mervis Hall",
                "type": "Workshop",
                "tags": "Business,Innovation,Students",
                "latitude": 40.4406,
                "longitude": -79.9959,
            },
            {
                "title": "Library Orientation",
                "description": "Discover the resources and facilities available at Hillman Library.",
                "time": timezone.now() + timezone.timedelta(days=6),
                "location": "University of Pittsburgh, Hillman Library",
                "type": "Orientation",
                "tags": "Library,Students,Resources",
                "latitude": 40.4422,
                "longitude": -79.9556,
            },
            {
                "title": "Career Fair",
                "description": "Meet potential employers and learn about career opportunities.",
                "time": timezone.now() + timezone.timedelta(days=7),
                "location": "University of Pittsburgh, William Pitt Union",
                "type": "Career Event",
                "tags": "Jobs,Students,Networking",
                "latitude": 40.4438,
                "longitude": -79.9535,
            },
            {
                "title": "Coding Hackathon",
                "description": "Join fellow students for 24 hours of coding and creativity.",
                "time": timezone.now() + timezone.timedelta(days=8),
                "location": "University of Pittsburgh, Benedum Hall",
                "type": "Hackathon",
                "tags": "Coding,Technology,Students",
                "latitude": 40.4436,
                "longitude": -79.9577,
            },
            {
                "title": "Music Jam Session",
                "description": "Bring your instruments and join us for an open jam session.",
                "time": timezone.now() + timezone.timedelta(days=9),
                "location": "University of Pittsburgh, Bellefield Hall",
                "type": "Music Event",
                "tags": "Music,Community,Students",
                "latitude": 40.4420,
                "longitude": -79.9563,
            },
            {
                "title": "Wellness Workshop",
                "description": "Learn tips and techniques for maintaining mental health.",
                "time": timezone.now() + timezone.timedelta(days=10),
                "location": "University of Pittsburgh, Nordenberg Hall",
                "type": "Health",
                "tags": "Wellness,Health,Students",
                "latitude": 40.4457,
                "longitude": -79.9530,
            },
            {
                "title": "Study Abroad Info Session",
                "description": "Explore the opportunities for studying abroad.",
                "time": timezone.now() + timezone.timedelta(days=11),
                "location": "University of Pittsburgh, Global Hub",
                "type": "Info Session",
                "tags": "Study Abroad,Students,Global",
                "latitude": 40.4423,
                "longitude": -79.9552,
            },
            {
                "title": "Debate Club Meeting",
                "description": "Join us to discuss and debate current topics.",
                "time": timezone.now() + timezone.timedelta(days=12),
                "location": "University of Pittsburgh, Cathedral of Learning Room 232",
                "type": "Club Meeting",
                "tags": "Debate,Community,Students",
                "latitude": 40.4425,
                "longitude": -79.9531,
            },
            {
                "title": "Photography Workshop",
                "description": "Learn the basics of photography and photo editing.",
                "time": timezone.now() + timezone.timedelta(days=13),
                "location": "University of Pittsburgh, Posvar Hall",
                "type": "Workshop",
                "tags": "Photography,Art,Students",
                "latitude": 40.4443,
                "longitude": -79.9607,
            },
            {
                "title": "Game Night",
                "description": "Enjoy board games and meet new friends.",
                "time": timezone.now() + timezone.timedelta(days=14),
                "location": "University of Pittsburgh, O'Hara Student Center",
                "type": "Social",
                "tags": "Games,Community,Students",
                "latitude": 40.4452,
                "longitude": -79.9554,
            },
            {
                "title": "Open Mic Night",
                "description": "Showcase your talent at our open mic event.",
                "time": timezone.now() + timezone.timedelta(days=15),
                "location": "University of Pittsburgh, William Pitt Union",
                "type": "Cultural",
                "tags": "Music,Performance,Students",
                "latitude": 40.4438,
                "longitude": -79.9535,
            },
            {
                "title": "Yoga in the Park",
                "description": "Relax and unwind with yoga in Schenley Park.",
                "time": timezone.now() + timezone.timedelta(days=16),
                "location": "Schenley Park, Pittsburgh",
                "type": "Health",
                "tags": "Yoga,Wellness,Students",
                "latitude": 40.4418,
                "longitude": -79.9463,
            },
            {
                "title": "Pitt Robotics Showcase",
                "description": "See what our robotics team has been building.",
                "time": timezone.now() - timezone.timedelta(days=17),
                "location": "University of Pittsburgh, Benedum Hall",
                "type": "Technology",
                "tags": "Robotics,Technology,Students",
                "latitude": 40.4436,
                "longitude": -79.9577,
            },
            {
                "title": "Student Film Screening",
                "description": "Watch short films made by Pitt students.",
                "time": timezone.now() - timezone.timedelta(days=18),
                "location": "University of Pittsburgh, Frick Fine Arts Building",
                "type": "Cultural",
                "tags": "Film,Art,Students",
                "latitude": 40.4416,
                "longitude": -79.9559,
            },
            {
                "title": "Welcome Back Bash",
                "description": "Start the semester with music, food, and fun.",
                "time": timezone.now() - timezone.timedelta(days=30),
                "location": "University of Pittsburgh, Schenley Quad",
                "type": "Social",
                "tags": "Welcome,Social,Students",
                "latitude": 40.4437,
                "longitude": -79.9532,
            },
            {
                "title": "Movie Night: Inception",
                "description": "Enjoy a screening of 'Inception' with snacks provided.",
                "time": timezone.now() - timezone.timedelta(days=7),
                "location": "University of Pittsburgh, William Pitt Union",
                "type": "Recreational",
                "tags": "Movie,Snacks,Social",
                "latitude": 40.4435,
                "longitude": -79.9543,
            },
            {
                "title": "Campus Cleanup Day",
                "description": "Join us to keep our campus clean and green.",
                "time": timezone.now() - timezone.timedelta(days=20),
                "location": "University of Pittsburgh, Cathedral Lawn",
                "type": "Community Service",
                "tags": "Cleanup,Volunteering,Environment",
                "latitude": 40.4446,
                "longitude": -79.9531,
            },
            {
                "title": "Midterm Stress Relief Yoga",
                "description": "Relax and destress with a guided yoga session.",
                "time": timezone.now() - timezone.timedelta(days=10),
                "location": "University of Pittsburgh, Gymnasium",
                "type": "Wellness",
                "tags": "Yoga,Stress Relief,Health",
                "latitude": 40.4442,
                "longitude": -79.9535,
            },
        ]

        for event_data in events:
            Event.objects.create(**event_data)

        self.stdout.write(self.style.SUCCESS('Successfully seeded the database with 25 specific events'))
