from django.core.management.base import BaseCommand
from events.models import Event
from django.utils import timezone
from accounts.models import CustomUser
from django.contrib.auth import get_user_model

class Command(BaseCommand):
    help = 'Seed the database with 25 specific university-related events in Pittsburgh'

    def handle(self, *args, **kwargs):
        # Bestehende Events löschen, um Duplikate zu vermeiden
        Event.objects.all().delete()

        # Benutzer-Modell abrufen
        User = get_user_model()

        # Manager erstellen
        manager, created = CustomUser.objects.get_or_create(
            username="event_manager",
            email="manager@example.com",
            defaults={"password": "securepassword123", "is_event_manager": True},
        )

        if created:
            self.stdout.write(self.style.SUCCESS('Event manager account created.'))


        # Events erstellen
        events = [
            {
                "title": "Campus Tour",
                "description": "Explore the University of Pittsburgh with a guided campus tour.",
                "time": timezone.now() + timezone.timedelta(days=1),
                "location": "University of Pittsburgh, Cathedral of Learning",
                "type": "Campus Event",
                "tags": "Campus,Students,Community",
                "latitude": 40.4425,
                "longitude": -79.9531,
                "organizer": manager,
            },
            {
                "title": "AI Research Seminar",
                "description": "Learn about the latest advancements in Artificial Intelligence.",
                "time": timezone.now() + timezone.timedelta(days=2),
                "location": "University of Pittsburgh, Information Science Building",
                "type": "Academic",
                "tags": "Research,Technology,Students",
                "latitude": 40.4445,
                "longitude": -79.9562,
                "organizer": manager,
            },
            {
                "title": "Football Night",
                "description": "Join us for a thrilling football game at Heinz Field.",
                "time": timezone.now() + timezone.timedelta(days=3),
                "location": "Heinz Field, Pittsburgh",
                "type": "Sports",
                "tags": "Sports,Community,Students",
                "latitude": 40.4470,
                "longitude": -80.0150,
                "organizer": manager,
            },
            {
                "title": "Pitt Arts Night",
                "description": "Experience an evening filled with art and culture at Pitt.",
                "time": timezone.now() + timezone.timedelta(days=4),
                "location": "University of Pittsburgh, Frick Fine Arts Building",
                "type": "Cultural",
                "tags": "Arts,Culture,Community",
                "latitude": 40.4416,
                "longitude": -79.9559,
                "organizer": manager,
            },
            {
                "title": "Entrepreneurship Workshop",
                "description": "Learn the basics of starting your own business.",
                "time": timezone.now() + timezone.timedelta(days=5),
                "location": "University of Pittsburgh, Mervis Hall",
                "type": "Workshop",
                "tags": "Business,Innovation,Students",
                "latitude": 40.4406,
                "longitude": -79.9959,
                "organizer": manager,
            },
            {
                "title": "Library Orientation",
                "description": "Discover the resources and facilities available at Hillman Library.",
                "time": timezone.now() + timezone.timedelta(days=6),
                "location": "University of Pittsburgh, Hillman Library",
                "type": "Orientation",
                "tags": "Library,Students,Resources",
                "latitude": 40.4422,
                "longitude": -79.9556,
                "organizer": manager,
            },
            {
                "title": "Career Fair",
                "description": "Meet potential employers and learn about career opportunities.",
                "time": timezone.now() + timezone.timedelta(days=7),
                "location": "University of Pittsburgh, William Pitt Union",
                "type": "Career Event",
                "tags": "Jobs,Students,Networking",
                "latitude": 40.4438,
                "longitude": -79.9535,
                "organizer": manager,
            },
            {
                "title": "Coding Hackathon",
                "description": "Join fellow students for 24 hours of coding and creativity.",
                "time": timezone.now() + timezone.timedelta(days=8),
                "location": "University of Pittsburgh, Benedum Hall",
                "type": "Hackathon",
                "tags": "Coding,Technology,Students",
                "latitude": 40.4436,
                "longitude": -79.9577,
                "organizer": manager,
            },
            {
                "title": "Music Jam Session",
                "description": "Bring your instruments and join us for an open jam session.",
                "time": timezone.now() + timezone.timedelta(days=9),
                "location": "University of Pittsburgh, Bellefield Hall",
                "type": "Music Event",
                "tags": "Music,Community,Students",
                "latitude": 40.4420,
                "longitude": -79.9563,
                "organizer": manager,
            },
            {
                "title": "Wellness Workshop",
                "description": "Learn tips and techniques for maintaining mental health.",
                "time": timezone.now() + timezone.timedelta(days=10),
                "location": "University of Pittsburgh, Nordenberg Hall",
                "type": "Health",
                "tags": "Wellness,Health,Students",
                "latitude": 40.4457,
                "longitude": -79.9530,
                "organizer": manager,
            },
            {
                "title": "Study Abroad Info Session",
                "description": "Explore the opportunities for studying abroad.",
                "time": timezone.now() + timezone.timedelta(days=11),
                "location": "University of Pittsburgh, Global Hub",
                "type": "Info Session",
                "tags": "Study Abroad,Students,Global",
                "latitude": 40.4423,
                "longitude": -79.9552,
                "organizer": manager,
            },
            {
                "title": "Debate Club Meeting",
                "description": "Join us to discuss and debate current topics.",
                "time": timezone.now() + timezone.timedelta(days=12),
                "location": "University of Pittsburgh, Cathedral of Learning Room 232",
                "type": "Club Meeting",
                "tags": "Debate,Community,Students",
                "latitude": 40.4425,
                "longitude": -79.9531,
                "organizer": manager,
            },
            {
                "title": "Photography Workshop",
                "description": "Learn the basics of photography and photo editing.",
                "time": timezone.now() + timezone.timedelta(days=13),
                "location": "University of Pittsburgh, Posvar Hall",
                "type": "Workshop",
                "tags": "Photography,Art,Students",
                "latitude": 40.4443,
                "longitude": -79.9607,
                "organizer": manager,
            },
            {
                "title": "Game Night",
                "description": "Enjoy board games and meet new friends.",
                "time": timezone.now() + timezone.timedelta(days=14),
                "location": "University of Pittsburgh, O'Hara Student Center",
                "type": "Social",
                "tags": "Games,Community,Students",
                "latitude": 40.4452,
                "longitude": -79.9554,
                "organizer": manager,
            },
            {
                "title": "Open Mic Night",
                "description": "Showcase your talent at our open mic event.",
                "time": timezone.now() + timezone.timedelta(days=15),
                "location": "University of Pittsburgh, William Pitt Union",
                "type": "Cultural",
                "tags": "Music,Performance,Students",
                "latitude": 40.4438,
                "longitude": -79.9535,
                "organizer": manager,
            },
            {
                "title": "Startup Pitch Night",
                "description": "Pitch your startup ideas to investors and get valuable feedback.",
                "time": timezone.now() + timezone.timedelta(days=16),
                "location": "University of Pittsburgh, Mervis Hall",
                "type": "Startup Event",
                "tags": "Business,Innovation,Entrepreneurship",
                "latitude": 40.4406,
                "longitude": -79.9959,
                "organizer": manager,
            },
            {
                "title": "TEDx Pitt Conference",
                "description": "A day of inspirational talks from diverse speakers.",
                "time": timezone.now() + timezone.timedelta(days=17),
                "location": "University of Pittsburgh, William Pitt Union",
                "type": "Conference",
                "tags": "TEDx,Inspiration,Technology,Ideas",
                "latitude": 40.4438,
                "longitude": -79.9535,
                "organizer": manager,
            },
            {
                "title": "Sustainability Fair",
                "description": "Explore sustainable practices and eco-friendly solutions.",
                "time": timezone.now() + timezone.timedelta(days=18),
                "location": "University of Pittsburgh, Schenley Plaza",
                "type": "Sustainability",
                "tags": "Sustainability,Environment,Community",
                "latitude": 40.4430,
                "longitude": -79.9545,
                "organizer": manager,
            },
            {
                "title": "VR Experience Night",
                "description": "Experience the latest in Virtual Reality technology.",
                "time": timezone.now() + timezone.timedelta(days=19),
                "location": "University of Pittsburgh, Benedum Hall",
                "type": "Technology",
                "tags": "Virtual Reality,Technology,Students",
                "latitude": 40.4436,
                "longitude": -79.9577,
                "organizer": manager,
            },
            {
                "title": "Hack the Planet",
                "description": "Join us for a 48-hour hackathon focused on solving global issues.",
                "time": timezone.now() + timezone.timedelta(days=20),
                "location": "University of Pittsburgh, Alumni Hall",
                "type": "Hackathon",
                "tags": "Hackathon,Technology,Innovation",
                "latitude": 40.4402,
                "longitude": -79.9543,
                "organizer": manager,
            },
            {
                "title": "Poetry Slam",
                "description": "Share your poetry or enjoy performances by talented poets.",
                "time": timezone.now() + timezone.timedelta(days=21),
                "location": "University of Pittsburgh, Cathedral of Learning",
                "type": "Cultural",
                "tags": "Poetry,Arts,Students",
                "latitude": 40.4425,
                "longitude": -79.9531,
                "organizer": manager,
            },
            {
                "title": "Environmental Science Symposium",
                "description": "Join experts to discuss pressing environmental issues and solutions.",
                "time": timezone.now() + timezone.timedelta(days=22),
                "location": "University of Pittsburgh, Environmental Science Department",
                "type": "Academic",
                "tags": "Environment,Science,Academic",
                "latitude": 40.4415,
                "longitude": -79.9530,
                "organizer": manager,
            },
            {
                "title": "Film Screening: Documentary Night",
                "description": "Watch and discuss a thought-provoking documentary film.",
                "time": timezone.now() + timezone.timedelta(days=23),
                "location": "University of Pittsburgh, Frick Fine Arts Building",
                "type": "Cultural",
                "tags": "Film,Documentary,Arts",
                "latitude": 40.4416,
                "longitude": -79.9559,
                "organizer": manager,
            },
            {
                "title": "Meditation and Yoga Session",
                "description": "Join us for a peaceful morning of meditation and yoga.",
                "time": timezone.now() - timezone.timedelta(days=24),
                "location": "University of Pittsburgh, Bellefield Hall",
                "type": "Health",
                "tags": "Wellness,Meditation,Yoga",
                "latitude": 40.4420,
                "longitude": -79.9563,
                "organizer": manager,
            },
            {
                "title": "Pittsburgh History Walk",
                "description": "Discover the history and culture of Pittsburgh on a guided walk.",
                "time": timezone.now() - timezone.timedelta(days=25),
                "location": "Pittsburgh, Downtown Area",
                "type": "Tour",
                "tags": "History,Culture,Community",
                "latitude": 40.4406,
                "longitude": -79.9959,
                "organizer": manager,
            },
            {
                "title": "Coding Bootcamp: Web Development",
                "description": "Learn the basics of web development in this hands-on coding bootcamp.",
                "time": timezone.now() - timezone.timedelta(days=26),
                "location": "University of Pittsburgh, Benedum Hall",
                "type": "Workshop",
                "tags": "Coding,Technology,Students",
                "latitude": 40.4436,
                "longitude": -79.9577,
                "organizer": manager,
            },
            {
                "title": "International Food Festival",
                "description": "Taste dishes from around the world and learn about different cultures.",
                "time": timezone.now() - timezone.timedelta(days=27),
                "location": "University of Pittsburgh, Schenley Plaza",
                "type": "Cultural",
                "tags": "Food,Culture,Community",
                "latitude": 40.4430,
                "longitude": -79.9545,
                "organizer": manager,
            },
            {
                "title": "Art Exhibit: Local Artists Showcase",
                "description": "Explore artwork created by local artists in this special exhibit.",
                "time": timezone.now() - timezone.timedelta(days=28),
                "location": "University of Pittsburgh, Frick Fine Arts Building",
                "type": "Cultural",
                "tags": "Art,Exhibition,Community",
                "latitude": 40.4416,
                "longitude": -79.9559,
                "organizer": manager,
            },
        ]

        # Events in die Datenbank einfügen
        for event_data in events:
            Event.objects.create(**event_data)

        self.stdout.write(self.style.SUCCESS('Successfully seeded the database with 25 specific events'))
